### PR TITLE
Fix notebook

### PR DESCRIPTION
**Pull request by bosonie**
Update the notebook for the eos analysis. We now support only the quantities described in the paper, meaning `epsilon`, `delta_per_formula_unit` and `nu`. We also remove the possibility to chose the prefactor (and the weights for `nu`), we fix them to the one described in the paper.
This makes the nootebok consistent with the results presented in [materials cloud](https://acwf-verification.materialscloud.org/), except for the color scale.

### CODE REVIEW

**Comment by bosonie** [comment]
@giovannipizzi, can you try the new notebook in your environment? I'm having trouble to use the `appmode` in my computer, but it is a general problem of `appmode` with new versions of jupyter I believe.

**Comment by giovannipizzi** [comment]
Thanks - for me it works (not perfect but it does) for 
```
appmode==0.9.0
widget_periodictable==3.1.1
```
(maybe you can add those references at the top of the two notebooks).

Also, I suggest to rename the file `show-GUI.ipynb` to `show-GUI-oxides.ipynb`.

However, the code crashes for some files (e.g. for the BigDFT one, since for some systems such as SiO the `num_atoms_in_sim_cell` is `None` in the JSON and this creates an exception.

Can you please check this out and see if this is easy to fix?

**Comment by bosonie** [comment]
@giovannipizzi, I implemented to force re-scale factor == 1 in case the number of atoms is not found. However I wonder what happens in the web-site. Are the data different there? We should ask @eimrek.
In any case, can you give another try to see that all is good?

**Comment by eimrek** [comment]
@bosonie I have a python notebook that transforms the data into a format that is used by the website. This transformation also includes scaling all energy and volume per atom.

Notebook: https://github.com/materialscloud-org/acwf-verification/blob/main/python/prepare_data.ipynb

final data: https://raw.githubusercontent.com/materialscloud-org/acwf-verification/main/src/data/data.json

Regarding what happens when `num_atoms_in_sim_cell` is `None`. interestingly' i don't have a check for this in my notebook, but also it doesn't except. However, I do check if `bm_fit` is `None`, then i skip the code/crystal. This probably means that e.g. for bigdft, they set `num_atoms_in_sim_cell` to `None` only if `bm_fit` is `None`.

**Comment by bosonie** [comment]
Thanks @eimrek . I just checked and you are correct, `num_atoms_in_sim_cell` is `None` when `BM_fit_data` is `None`. So one of the two checks is sufficient.

**Comment by giovannipizzi** [comment]
I have upgraded various Jupyter dependencies and fixed a few bugs. I spent a few hours on this but I don't have much time for further debugging, so I put a disclaimer that we do not guarantee everything is fully correct, and to use the plotting scripts that we used in the paper instead

**Pull request merged**
