### PR TITLE
Add PseudoDojo results for QE and CASTEP

### PR DESCRIPTION
**Pull request by mbercx**
Add the PseudoDojo-0.4-PBE-SR-standard results for Quantum ESPRESSO and CASTEP, using the trimmed UPF files generated by @zhubonan.

Add the corresponding labels to the `labels.json` file so the data can be picked up by the plotting scripts.

Add a `LABELS_KEY` to the `generate_all_periodic_table.py` script, so e.g. the `"methods-supplementary"` data labels can also be accessed.

### CODE REVIEW

**Comment by mbercx** [comment]
@zhubonan I immediately added the CASTEP results for the trimmed UPF files as well, since I had them anyways and I think @eimrek needs them to update the plots. Hope that's ok!

Let me know if you've still updated them with e.g. higher cutoff runs.

**Comment by zhubonan** [comment]
No problem at all.
Maybe we should also deposit the trimmed files somewhere or including the trimming script in the repo?

**Review by zhubonan — APPROVED** [review]
Looks good to me!

**Comment by mbercx** [comment]
@zhubonan quick follow-up: can I find the script to trim the pseudos somewhere? @unkcpz was interested in doing some tests with trimming UPFs.

**Comment by zhubonan** [comment]
I remember it was sent via slack 😅

**Comment by unkcpz** [comment]
haha, I think using slack to transfer files is against "FAIR" principle, probably in the future an `aiida-slack` plugin is needed to make it reproducible 🤣

**Comment by zhubonan** [comment]
lol. Anyway, I can try to dig it up, but it may take some time. @mbercx may be check your 'Downloads' folder (if you don't have a habit of clearing it) or other people on who might have received it.

**Comment by mbercx** [comment]
> @mbercx may be check your 'Downloads' folder (if you don't have a habit of clearing it) or other people on who might have received it.

I'm afraid I'm too tidy. 😅 Maybe @azadoks or @sponce24 still saved it somewhere? I'll also touch base with them on Slack.

**Comment by zhubonan** [comment]
I can try to dig it up from backup archive, but it may take some time.

**Comment by unkcpz** [comment]
Hi @zhubonan, it'll be great if you can find it. Or could you give me some hints on which modification you made to the file? Did you discard the values with lower rcut or are you smoothing the behavior on the local potential?

**Comment by zhubonan** [comment]
I simply cropped the potential at the described cut off, e.g. the values beyond the cut off are discarded.

**Comment by unkcpz** [comment]
Thanks, that is important information.  Did you crop on local potential only or also the pseudo wavefunctions and projectors?

**Comment by zhubonan** [comment]
I think it was just one quantity. The goal is to simulate what Abinit does when it reads the upf by modifying the upf itself.

**Comment by unkcpz** [comment]
I regenerate trimmed UPF files and upload those in https://github.com/unkcpz/sssp-verify-scripts/tree/main/libraries-pbe/NC-DOJOv0.5-standard-trim
Since I am not sure if it is correct to trim the pseudo-wavefunction with the mesh and since it is not used in EOS calculation, I discard "PP_PSWFC".

**Pull request merged**
